// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/GetImageCd/GetImageCd.proto

package go_micro_srv_GetImageCd

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message struct {
	Say                  string   `protobuf:"bytes,1,opt,name=say,proto3" json:"say,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_208a871f55559f63, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetSay() string {
	if m != nil {
		return m.Say
	}
	return ""
}

type Request struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=Uuid,proto3" json:"Uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_208a871f55559f63, []int{1}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

type Response struct {
	Error  string `protobuf:"bytes,1,opt,name=Error,proto3" json:"Error,omitempty"`
	Errmsg string `protobuf:"bytes,2,opt,name=Errmsg,proto3" json:"Errmsg,omitempty"`
	// 图片对象的零件,层层递进的获取（因proto没有映射图像
	Pix                  []byte          `protobuf:"bytes,3,opt,name=Pix,proto3" json:"Pix,omitempty"`
	Stride               int64           `protobuf:"zigzag64,4,opt,name=Stride,proto3" json:"Stride,omitempty"`
	Min                  *Response_Point `protobuf:"bytes,5,opt,name=Min,proto3" json:"Min,omitempty"`
	Max                  *Response_Point `protobuf:"bytes,6,opt,name=Max,proto3" json:"Max,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_208a871f55559f63, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *Response) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

func (m *Response) GetPix() []byte {
	if m != nil {
		return m.Pix
	}
	return nil
}

func (m *Response) GetStride() int64 {
	if m != nil {
		return m.Stride
	}
	return 0
}

func (m *Response) GetMin() *Response_Point {
	if m != nil {
		return m.Min
	}
	return nil
}

func (m *Response) GetMax() *Response_Point {
	if m != nil {
		return m.Max
	}
	return nil
}

type Response_Point struct {
	X                    int64    `protobuf:"zigzag64,1,opt,name=X,proto3" json:"X,omitempty"`
	Y                    int64    `protobuf:"zigzag64,2,opt,name=Y,proto3" json:"Y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response_Point) Reset()         { *m = Response_Point{} }
func (m *Response_Point) String() string { return proto.CompactTextString(m) }
func (*Response_Point) ProtoMessage()    {}
func (*Response_Point) Descriptor() ([]byte, []int) {
	return fileDescriptor_208a871f55559f63, []int{2, 0}
}

func (m *Response_Point) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response_Point.Unmarshal(m, b)
}
func (m *Response_Point) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response_Point.Marshal(b, m, deterministic)
}
func (m *Response_Point) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response_Point.Merge(m, src)
}
func (m *Response_Point) XXX_Size() int {
	return xxx_messageInfo_Response_Point.Size(m)
}
func (m *Response_Point) XXX_DiscardUnknown() {
	xxx_messageInfo_Response_Point.DiscardUnknown(m)
}

var xxx_messageInfo_Response_Point proto.InternalMessageInfo

func (m *Response_Point) GetX() int64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Response_Point) GetY() int64 {
	if m != nil {
		return m.Y
	}
	return 0
}

func init() {
	proto.RegisterType((*Message)(nil), "go.micro.srv.GetImageCd.Message")
	proto.RegisterType((*Request)(nil), "go.micro.srv.GetImageCd.Request")
	proto.RegisterType((*Response)(nil), "go.micro.srv.GetImageCd.Response")
	proto.RegisterType((*Response_Point)(nil), "go.micro.srv.GetImageCd.Response.Point")
}

func init() {
	proto.RegisterFile("proto/GetImageCd/GetImageCd.proto", fileDescriptor_208a871f55559f63)
}

var fileDescriptor_208a871f55559f63 = []byte{
	// 276 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0x4f, 0x4b, 0x03, 0x31,
	0x10, 0xc5, 0x8d, 0xfb, 0xa7, 0x3a, 0xf6, 0x20, 0x83, 0x68, 0xa8, 0x08, 0xdb, 0xf5, 0xe0, 0x9e,
	0x22, 0xd4, 0x93, 0xe7, 0x52, 0xc4, 0xc3, 0x42, 0x89, 0x08, 0x2d, 0x9e, 0xa2, 0x1b, 0x96, 0x40,
	0x77, 0x53, 0x93, 0x54, 0xd6, 0x0f, 0x2f, 0x48, 0xe2, 0x4a, 0xbd, 0xa8, 0xf4, 0xf6, 0x7e, 0x99,
	0x79, 0x99, 0x79, 0x09, 0x8c, 0xd7, 0x46, 0x3b, 0x7d, 0x7d, 0x27, 0xdd, 0x7d, 0x23, 0x6a, 0x39,
	0xad, 0x7e, 0x48, 0x16, 0x6a, 0x78, 0x56, 0x6b, 0xd6, 0xa8, 0x17, 0xa3, 0x99, 0x35, 0x6f, 0x6c,
	0x5b, 0xce, 0xcf, 0x61, 0x50, 0x4a, 0x6b, 0x45, 0x2d, 0xf1, 0x18, 0x22, 0x2b, 0xde, 0x29, 0xc9,
	0x48, 0x71, 0xc8, 0xbd, 0xcc, 0x2f, 0x60, 0xc0, 0xe5, 0xeb, 0x46, 0x5a, 0x87, 0x08, 0xf1, 0xe3,
	0x46, 0x55, 0x7d, 0x35, 0xe8, 0xfc, 0x83, 0xc0, 0x01, 0x97, 0x76, 0xad, 0x5b, 0x2b, 0xf1, 0x04,
	0x92, 0x99, 0x31, 0xda, 0xf4, 0x1d, 0x5f, 0x80, 0xa7, 0x90, 0xce, 0x8c, 0x69, 0x6c, 0x4d, 0xf7,
	0xc3, 0x71, 0x4f, 0x7e, 0xd6, 0x5c, 0x75, 0x34, 0xca, 0x48, 0x31, 0xe4, 0x5e, 0xfa, 0xce, 0x07,
	0x67, 0x54, 0x25, 0x69, 0x9c, 0x91, 0x02, 0x79, 0x4f, 0x78, 0x0b, 0x51, 0xa9, 0x5a, 0x9a, 0x64,
	0xa4, 0x38, 0x9a, 0x5c, 0xb1, 0x5f, 0x72, 0xb0, 0xef, 0x3d, 0xd8, 0x5c, 0xab, 0xd6, 0x71, 0xef,
	0x09, 0x56, 0xd1, 0xd1, 0x74, 0x57, 0xab, 0xe8, 0x46, 0x97, 0x90, 0x04, 0xc2, 0x21, 0x90, 0x45,
	0x88, 0x84, 0x9c, 0x2c, 0x3c, 0x2d, 0x43, 0x12, 0xe4, 0x64, 0x39, 0x79, 0x02, 0xd8, 0x5e, 0x83,
	0x25, 0xc4, 0x53, 0xb1, 0x5a, 0x61, 0xf6, 0xc7, 0xa0, 0xf0, 0x96, 0xa3, 0xf1, 0xbf, 0xab, 0xe4,
	0x7b, 0xcf, 0x69, 0xf8, 0xb8, 0x9b, 0xcf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb4, 0xf4, 0x4d, 0xc7,
	0xdd, 0x01, 0x00, 0x00,
}
